---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r setupoptions, include=FALSE}
library(knitr)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
library(lubridate)
library(lattice)
opts_chunk$set(echo= TRUE)
```

## Loading and preprocessing the data
```{r loadData}

file <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r mean/median}
temp <- file %>% group_by(date) %>% summarise(total = sum(steps)) %>% mutate(date = as.Date(date))

qplot(total, data = temp, xlab = "total steps per day", ylab = "frequency",)
sprintf("Mean: %f", mean(temp$total,na.rm = TRUE))
sprintf("Median: %f", median(temp$total, na.rm = TRUE))

```


## What is the average daily activity pattern?
```{r avgInt}

temp <- file %>% drop_na(steps) %>% group_by(interval) %>% summarise(avg = mean(steps))
qplot(interval, avg, data = temp, geom = "line")

maxInt <- temp$interval[which.max(temp$avg)]
sprintf("Max Interval is %i", maxInt)

```

## Imputing missing values
Impute by median of the interval
```{r input}

sumNa <- sum(is.na(file$steps))
sprintf("Sum of row with NA is %i", sumNa)

fileNoNa <- file %>% group_by(interval) %>% mutate(newsteps = ifelse(is.na(steps),mean(steps,na.rm = TRUE),steps))

temp1 <- fileNoNa %>% summarise(total = sum(steps))

qplot(total, data = temp1)

sprintf("Mean: %f", mean(temp1$total,na.rm = TRUE))
sprintf("Median: %f", median(temp1$total, na.rm = TRUE))

```

## Are there differences in activity patterns between weekdays and weekends?
```{r diff}

bool <- wday(ymd(file$date)) %in% c(1,7)

temp <- file %>% drop_na(steps) %>% mutate(wday = ifelse(wday(ymd(date)) %in% c(1,7), "weekend", "weekday")) %>% group_by(wday,interval) %>% summarise(avg = mean(steps))

qplot(interval, avg, data = temp, geom = "line", facets = wday~"" )
```
